In [1]:
import torch
import numpy as np

np.set_printoptions(precision=3)
a = [1,2,3]
b = np.array([4,5,6], dtype=np.int32)
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)
print(t_a)
print(t_b)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [3]:
t_ones = torch.ones(2,3)
print(t_ones.shape)
t_ones

torch.Size([2, 3])


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [5]:
rand_tensor = torch.rand(2,3)
print(rand_tensor)

tensor([[0.4936, 0.4539, 0.5863],
        [0.2031, 0.6899, 0.2898]])


In [6]:
t_a_new = t_a.to(torch.int64)
print(t_a_new.dtype)

torch.int64


In [7]:
t = torch.rand(3,5)
t_tr = torch.transpose(t, 0, 1)
print(t.shape, '--->', t_tr.shape)

torch.Size([3, 5]) ---> torch.Size([5, 3])
