In [1]:
import torch
import numpy as np

np.set_printoptions(precision=3)
a = [1,2,3]
b = np.array([4,5,6], dtype=np.int32)
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)
print(t_a)
print(t_b)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [3]:
t_ones = torch.ones(2,3)
print(t_ones.shape)
t_ones

torch.Size([2, 3])


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [5]:
rand_tensor = torch.rand(2,3)
print(rand_tensor)

tensor([[0.4936, 0.4539, 0.5863],
        [0.2031, 0.6899, 0.2898]])


In [6]:
t_a_new = t_a.to(torch.int64)
print(t_a_new.dtype)

torch.int64


In [7]:
t = torch.rand(3,5)
t_tr = torch.transpose(t, 0, 1)
print(t.shape, '--->', t_tr.shape)

torch.Size([3, 5]) ---> torch.Size([5, 3])


In [8]:
t = torch.zeros(30)
t_reshape = t.reshape(5,6)
print(t_reshape)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


In [9]:
t = torch.zeros(1,2,1,4,1)
t_sqz = torch.squeeze(t,2) #take out 2nd dimension
print(t.shape, '-->',t_sqz.shape)

torch.Size([1, 2, 1, 4, 1]) --> torch.Size([1, 2, 4, 1])


In [10]:
t1 = 2 * torch.rand(5,2) - 1 #uniform distribution
t2 = torch.normal(mean=0, std=1,size=(5,2)) #normal distribution
t3 = torch.multiply(t1, t2) #elementwise product
print(t3)

tensor([[ 0.3087,  1.4848],
        [ 0.0446, -0.2088],
        [ 0.5379,  0.0702],
        [ 0.1149, -0.0714],
        [-0.3491,  0.3353]])
